# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
POST http://127.0.0.1
content-type: application/json

{
    "cart_value": 790,
    "delivery_distance": 2235,
    "number_of_items": 4,
    "time": "2021-10-12T13:00:00Z"
}
